# Generated by Django 4.1.6 on 2023-02-06 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_deck_author_alter_deck_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sss', related_query_name='%(class)s', to='flashcards.difficultylevel'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sss', related_query_name='%(class)s', to='flashcards.difficultylevel'),
        ),
    ]
