# Generated by Django 4.1.6 on 2023-02-07 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0007_alter_deck_author_alter_deck_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deck',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='flashcards.difficultylevel'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='tags',
            field=models.ManyToManyField(related_name='%(class)s', to='flashcards.tag'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='flashcards.difficultylevel'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='tags',
            field=models.ManyToManyField(related_name='%(class)s', to='flashcards.tag'),
        ),
    ]
